name: rust-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest,
                    macos-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: rustup update stable
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.3.0
    - name: Format
      run: cargo fmt -- --check
    - name: Run clippy
      run: cargo clippy --verbose -- -D warnings
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
